[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.python"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[deploy.environmentVariables]]
name = "GOTENBERG_URL"
value = "https://simplegym-gotenberg-production.up.railway.app"

[[deploy.environmentVariables]]
name = "ENVIRONMENT"
value = "production"
